CL_DynTFTTrackBar_EnabledBackground = CL_BLUECHARCOAL02;
CL_DynTFTTrackBar_DisabledBackground = CL_BLUECHARCOAL10;
CL_DynTFTTrackBar_PanelBackground = CL_BLUECHARCOAL06;
CL_DynTFTTrackBar_EnabledNotch = CL_BLUECHARCOAL13;
CL_DynTFTTrackBar_DisabledNotch = CL_BLUECHARCOAL01;
CL_DynTFTTrackBar_EnabledTick = CL_BLUECHARCOAL12;
CL_DynTFTTrackBar_DisabledTick = CL_BLUECHARCOAL04;
CL_DynTFTTrackBar_LightEdge = CL_BLUECHARCOAL15;
