CL_DynTFTTrackBar_EnabledBackground = CL_LEMONCHARCOAL02;
CL_DynTFTTrackBar_DisabledBackground = CL_LEMONCHARCOAL10;
CL_DynTFTTrackBar_PanelBackground = CL_LEMONCHARCOAL05;
CL_DynTFTTrackBar_EnabledNotch = CL_LEMONCHARCOAL13;
CL_DynTFTTrackBar_DisabledNotch = CL_LEMONCHARCOAL01;
CL_DynTFTTrackBar_EnabledTick = CL_LEMONCHARCOAL12;
CL_DynTFTTrackBar_DisabledTick = CL_LEMONCHARCOAL04;
CL_DynTFTTrackBar_LightEdge = CL_LEMONCHARCOAL15;
