CL_DynTFTTrackBar_EnabledBackground = CL_REDCHARCOAL02;
CL_DynTFTTrackBar_DisabledBackground = CL_REDCHARCOAL10;
CL_DynTFTTrackBar_PanelBackground = CL_REDCHARCOAL06;
CL_DynTFTTrackBar_EnabledNotch = CL_REDCHARCOAL13;
CL_DynTFTTrackBar_DisabledNotch = CL_REDCHARCOAL01;
CL_DynTFTTrackBar_EnabledTick = CL_REDCHARCOAL12;
CL_DynTFTTrackBar_DisabledTick = CL_REDCHARCOAL04;
CL_DynTFTTrackBar_LightEdge = CL_REDCHARCOAL15;
