{   DynTFT  - graphic components for microcontrollers
    Copyright (C) 2017 VCC
    release date: 29 Dec 2017
    author: VCC

    This file is part of DynTFT project.

    DynTFT is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, version 3 of the License.

    DynTFT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with DynTFT, in COPYING.LESSER file.
    If not, see <http://www.gnu.org/licenses/>.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
    OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
}

  {$I DynTFT_MatrixColors\DynTFTArrowButton_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTButton_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTCheckBox_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTEdit_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTItems_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTKeyButton_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTLabel_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTListBox_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTMessageBox_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTPanel_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTProgressBar_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTRadioButton_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTRadioGroup_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTScreen_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTScrollBar_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTTabButton_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTTrackBar_MatrixColors.inc}
  {$I DynTFT_MatrixColors\DynTFTVirtualKeyboard_MatrixColors.inc}