CL_DynTFTTrackBar_EnabledBackground = CL_GREENCHARCOAL02;
CL_DynTFTTrackBar_DisabledBackground = CL_GREENCHARCOAL10;
CL_DynTFTTrackBar_PanelBackground = CL_GREENCHARCOAL05;
CL_DynTFTTrackBar_EnabledNotch = CL_GREENCHARCOAL13;
CL_DynTFTTrackBar_DisabledNotch = CL_GREENCHARCOAL01;
CL_DynTFTTrackBar_EnabledTick = CL_GREENCHARCOAL12;
CL_DynTFTTrackBar_DisabledTick = CL_GREENCHARCOAL04;
CL_DynTFTTrackBar_LightEdge = CL_GREENCHARCOAL15;
