{   DynTFT  - graphic components for microcontrollers
    Copyright (C) 2017, 2022 VCC
    initial release date: 29 Dec 2017
    author: VCC

    This file is part of DynTFT project.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this file,
    You can obtain one at https://mozilla.org/MPL/2.0/.

    Copyright (c) 2022, VCC  https://github.com/VCC02

    Alternatively, the contents of this file may be used under the terms
    of the GNU Lesser General Public License Version 3, as described below:

    DynTFT is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, version 3 of the License.

    DynTFT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with DynTFT, in COPYING.LESSER file.
    If not, see <http://www.gnu.org/licenses/>.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
    OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
}

  CL_ORCHID01 = {$IFDEF IsDesktop} $00FF96C8; {$ELSE} $CCBF; {$ENDIF}
  CL_ORCHID02 = {$IFDEF IsDesktop} $00FF3192; {$ELSE} $919F; {$ENDIF}
  CL_ORCHID03 = {$IFDEF IsDesktop} $00F18ECC; {$ELSE} $CC7E; {$ENDIF}
  CL_ORCHID04 = {$IFDEF IsDesktop} $00DA679E; {$ELSE} $9B3B; {$ENDIF}
  CL_ORCHID05 = {$IFDEF IsDesktop} $008B4B5F; {$ELSE} $5A51; {$ENDIF}
  CL_ORCHID06 = {$IFDEF IsDesktop} $00B77F8F; {$ELSE} $8BF6; {$ENDIF}
  CL_ORCHID07 = {$IFDEF IsDesktop} $00EA53C7; {$ELSE} $C29D; {$ENDIF}
  CL_ORCHID08 = {$IFDEF IsDesktop} $008A3666; {$ELSE} $61B1; {$ENDIF}
  CL_ORCHID09 = {$IFDEF IsDesktop} $00502039; {$ELSE} $390A; {$ENDIF}
  CL_ORCHID10 = {$IFDEF IsDesktop} $00F4A8E1; {$ELSE} $E55E; {$ENDIF}
  CL_SCREENBK = {$IFDEF IsDesktop} $00DFA6C6; {$ELSE} $C53B; {$ENDIF}
