CL_DynTFTTrackBar_EnabledBackground = CL_YELLOWCHARCOAL02;
CL_DynTFTTrackBar_DisabledBackground = CL_YELLOWCHARCOAL10;
CL_DynTFTTrackBar_PanelBackground = CL_YELLOWCHARCOAL05;
CL_DynTFTTrackBar_EnabledNotch = CL_YELLOWCHARCOAL13;
CL_DynTFTTrackBar_DisabledNotch = CL_YELLOWCHARCOAL01;
CL_DynTFTTrackBar_EnabledTick = CL_YELLOWCHARCOAL12;
CL_DynTFTTrackBar_DisabledTick = CL_YELLOWCHARCOAL04;
CL_DynTFTTrackBar_LightEdge = CL_YELLOWCHARCOAL15;
