CL_DynTFTTrackBar_EnabledBackground = CL_CHARCOAL02;
CL_DynTFTTrackBar_DisabledBackground = CL_CHARCOAL10;
CL_DynTFTTrackBar_PanelBackground = CL_CHARCOAL05;
CL_DynTFTTrackBar_EnabledNotch = CL_CHARCOAL07;
CL_DynTFTTrackBar_DisabledNotch = CL_CHARCOAL01;
CL_DynTFTTrackBar_EnabledTick = CL_CHARCOAL01;
CL_DynTFTTrackBar_DisabledTick = CL_CHARCOAL04;
CL_DynTFTTrackBar_LightEdge = CL_CHARCOAL01;
